### ISSUE TITLE
add number recognition

### ISSUE THREAD

**Issue by Spp595** [dekiesel/wyoming-vosk-standalone#1]
there is a library in python that recognizes numbers https://github.com/allo-media/text2num
is it possible to insert it into a container?

**Comment by dekiesel** [comment]
It is possible to add that library to the container, but you'd need to rewrite vosk's code to actually use it. 

Imo you have two options: Add your voice to the issue on the vosk repo or use something like [appdaemon](https://github.com/AppDaemon/appdaemon) or pyscript to use that library in your automation, meaning:

1. Set up your sentence recognition
2. Write a Home Assistant intent that [re-emits your intent as an event](https://www.home-assistant.io/docs/automation/trigger/#event-trigger)
3. Write an appdaemon automation that calls text2num on the event-data

**Comment by Spp595** [comment]
Is it possible to transfer the received text from vosk to t2n and then to Wyoming protocol?

**Comment by dekiesel** [comment]
You'll likely need to change the library: https://github.com/rhasspy/wyoming-vosk

This repo really just holds other peoples work with a bit of orchestration around it.
